---
development:
  cloud_name: sasaranandrei
  api_key: '788924322271915'
  api_secret: ZIbGl7lULuQlx8Y4WgQhjzfQ6ao
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: sasaranandrei
  api_key: '788924322271915'
  api_secret: ZIbGl7lULuQlx8Y4WgQhjzfQ6ao
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: sasaranandrei
  api_key: '788924322271915'
  api_secret: ZIbGl7lULuQlx8Y4WgQhjzfQ6ao
  enhance_image_tag: true
  static_file_support: false
