default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: food_ordering_development

test:
  <<: *default
  database: food_ordering_test

production:
  <<: *default
  database: food_ordering_production
  username: food_ordering
  password: <%= ENV['FOOD_ORDERING_DATABASE_PASSWORD'] %>
